name: Generate ARM templates docs
on:
  push:
    branches: [ main ]
jobs:
  arm_docs:
    name: Generate ARM template docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Reference Documentation
      id: Container_Name
      run: |
        Install-Module -Name 'PSDocs.Azure' -Repository PSGallery -force;
        Get-AzDocTemplateFile | ForEach-Object {
          $TemplateFile = Get-Item -Path $_.TemplateFile;
          $Template = Get-Content $TemplateFile |ConvertFrom-Json;
          $ContentVersion = $Template.ContentVersion;
          Invoke-PSDocument -Module PSDocs.Azure -OutputPath "out/docs" -InputObject $TemplateFile.FullName -InstanceName $TemplateFile.BaseName;
        };
        New-Item docs -ItemType Directory -Force;
        Move-Item "out/docs/azuredeploy.md" README.md -Force;
        Move-Item "out/docs/*.md" docs/ -Force;
        echo "::set-output name=CONTAINER::$($ContentVersion)"
      shell: pwsh
    - name: Setup Git Config
      run:
        git config user.name "GitHub Action";
        git config user.email "<>";
    - name: Update ReadME
      run:
        ls
        #git add *;
        #git commit -m "Updating README with latest documentation";
        #git push origin main
    - name: Send to Azure Storage Account
      uses: azure/CLI@v1
      with:
        azcliversion: 2.34.1
        inlinescript: |
          az storage blob upload-batch --source reference --destination ${{steps.Container_Name.outputs.CONTAINER}} --connection-string ${{ secrets.ConnectionString }} --destination-path Microsoft.RecoveryServices/reference
